name: weather_app
description: "Anither one weather app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  auto_route: ^9.3.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  json_serializable: ^6.9.0
  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
