name: weather_app
description: "Another one weather app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  auto_route: ^9.3.0+1
  equatable: ^2.0.5
  geolocator: ^13.0.2
  rxdart: ^0.28.0
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  json_serializable: ^6.9.0
  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
